// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cortMonteCarlo
Rcpp::NumericMatrix cortMonteCarlo(const NumericMatrix z, const NumericMatrix min, const NumericMatrix max, const int N);
RcppExport SEXP _cort_cortMonteCarlo(SEXP zSEXP, SEXP minSEXP, SEXP maxSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type z(zSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type min(minSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type max(maxSEXP);
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(cortMonteCarlo(z, min, max, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cort_cortMonteCarlo", (DL_FUNC) &_cort_cortMonteCarlo, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_cort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
