# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bivRho <- function(a, b, p) {
    .Call(`_cort_bivRho`, a, b, p)
}

bivTau <- function(a, b, p) {
    .Call(`_cort_bivTau`, a, b, p)
}

cortMonteCarlo <- function(z, min, max, N) {
    .Call(`_cort_cortMonteCarlo`, z, min, max, N)
}

lossFunc <- function(bp, bin_repr, z) {
    .Call(`_cort_lossFunc`, bp, bin_repr, z)
}

quadProd <- function(a, b, kern, other_a, other_b, other_kern) {
    .Call(`_cort_quadProd`, a, b, kern, other_a, other_b, other_kern)
}

