# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cortMonteCarlo <- function(z, min, max, N) {
    .Call(`_cort_cortMonteCarlo`, z, min, max, N)
}

